build: off
clone_depth: 5
configuration: Release

environment:
  PKG_NAME: pandas_plink
  matrix:
    - platform: x64
      ARCH: x64
      PYTHON: C:\Python37-x64
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* *-win32
    - platform: x86
      ARCH: x86
      PYTHON: C:\Python37
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* *-win_amd64

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "%PYTHON%\\python.exe -m pip install cibuildwheel>=0.9.1"

build_script:
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
  - "%PYTHON%\\python.exe -m cibuildwheel --output-dir wheelhouse"
  - FOR %%F IN (wheelhouse\*.whl) DO set filename=%%F
  - "%PYTHON%\\python.exe -m pip install %filename%"
  - cd ..
  - "%PYTHON%\\python.exe -c \"import pandas_plink; import sys; sys.exit(pandas_plink.test())\""
  - cd %APPVEYOR_BUILD_FOLDER%
  - if [%APPVEYOR_REPO_TAG%]==[true] (%PYTHON%\python.exe -m pip install twine && %PYTHON%\python.exe -m twine upload --skip-existing wheelhouse/*)

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
