name: root
channels:
- defaults
dependencies:
- alabaster=0.7.9=py35_0
- babel=2.3.4=py35_0
- cffi=1.8.3=py35_0
- docutils=0.12=py35_2
- imagesize=0.7.1=py35_0
- jinja2=2.8=py35_1
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- llvmlite=0.14.0=py35_0
- markupsafe=0.23=py35_2
- nomkl=1.0=0
- numpy=1.11.2=py35_nomkl_0
- openblas=0.2.14=4
- openssl=1.0.2h=1
- pip=9.0.1=py35_0
- pycosat=0.6.1=py35_1
- pycparser=2.17=py35_0
- pycrypto=2.6.1=py35_4
- pygments=2.1.3=py35_0
- python=3.5.2=0
- pytz=2016.7=py35_0
- pyyaml=3.11=py35_4
- readline=6.2=2
- requests=2.10.0=py35_0
- ruamel_yaml=0.11.14=py35_0
- setuptools=23.0.0=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.4.8=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pandas=0.19.1
- pip:
  - sphinx-rtd-theme==0.1.9
